### ISSUE TITLE
Error: NoFSMFound

### ISSUE THREAD

**Issue by vgarcialatorre** [vstirbu/fsm2dot#6]
Hi, 

I have been trying to use this tool but I keep getting this error

```
Error: NoFSMFound
    at module.exports (/usr/local/lib/node_modules/fsm2dot/lib/finder.js:59:11)
    at module.exports (/usr/local/lib/node_modules/fsm2dot/lib/graph.js:10:13)
    at Object.<anonymous> (/usr/local/lib/node_modules/fsm2dot/index.js:26:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

I run this 
`fsm2dot -f fsm.js -o fsm.dot `

And fsm.js is exactly the one from the example here: 
https://github.com/vstirbu/fsm2dot/blob/master/example/fsm.js

Why am I getting that error? 

Thanks for your help.

**Comment by vstirbu** [comment]
Oh, seems that the example is outdated. The snippet needs to include:

```javascript
var StateMachine = require('fsm-as-promised');
```
or
```javascript
var StateMachine = require('javascript-state-machine');
```

I'll update the documentation! thanks for pointing out.

**Comment by vgarcialatorre** [comment]
It worked!
Thanks
